name: CI
on: [ pull_request, push ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install dependencies
        run: pip install tox
      - name: Run pytest
        run: tox -e pytest
  pylama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install dependencies
        run: pip install tox
      - name: Run pylama
        run: tox -e pylama
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install dependencies
        run: pip install tox
      - name: Run mypy
        run: tox -e mypy
